import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { Header } from "../components/header"
import { SearchBar } from "../components/searchBar"
import { HotelPreview } from "../components/hotelPreview"

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col text-gray-900 relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SearchBar />
      <HotelPreview />{" "}
    </div>
  )
}
